### ISSUE TITLE
Does not work on Firefox ESR 68.6 in the mode network.trr.mode=3

### ISSUE THREAD

**Issue by wvxwxvw** [floreo/WebsiteIP#2]
Does not work on Firefox ESR 68.6 in the mode network.trr.mode=3

**Comment by wvxwxvw** [comment]
At the same time FlagFox and Сounry Flags they continue to work.

**Comment by floreo** [comment]
Hello,

thanks for reporting this. I'll dig into it ASAP.

**Comment by floreo** [comment]
The new version will be published soon in the firefox addons  ;)

**Comment by wvxwxvw** [comment]
Yes, it's all right.
